#
# docker-compose up -d --build
#
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - php_xdebug_log=/var/task/xdebug-errors.log
    volumes:
      - ~/.npmrc:/root/.npmrc
      - .:/var/task
